In [1]:
import pandas as pd

In [2]:
diy_df = pd.read_csv("../data/train_grouped_mean.csv")
original_df = pd.read_csv("../data/training_data_means.csv")

In [3]:
diy_df.head(5)

,sgrna_symbol,A1BG,A1CF,AADAC,AAK1,AARS1,AASS,ABCA1,ABCA12,ABCA5,...,ZP3,ZPBP,ZRANB3,ZSCAN18,ZSCAN31,ZSWIM5,ZSWIM6,ZSWIM7,ZWINT,ZYX
0,ACLY,0.311642,0.022102,0.100949,0.378671,0.715857,0.000000,0.118900,0.030792,0.087006,...,0.290693,0.002349,0.638608,0.031022,0.036856,0.097390,0.914845,0.647727,0.720461,0.603572
1,ALDOA,0.627445,0.043961,0.094335,0.442062,0.658125,0.000000,0.200191,0.000000,0.061549,...,0.390909,0.000000,0.371624,0.045867,0.087408,0.124600,0.821529,0.801302,0.545344,0.553567
2,APAF1,0.467114,0.030714,0.090910,0.470155,0.732770,0.002820,0.118370,0.025851,0.137382,...,0.359183,0.000000,0.535496,0.009991,0.053445,0.069219,0.855117,0.709241,0.674747,0.667791
3,ARID2,0.517185,0.018776,0.102561,0.445692,0.687079,0.010236,0.124519,0.016378,0.123456,...,0.353383,0.000000,0.557026,0.017552,0.062452,0.094811,0.731613,0.614643,0.629297,0.619404
4,BAG1,0.409021,0.034862,0.129969,0.462849,0.819877,0.002999,0.125579,0.002677,0.131047,...,0.286078,0.000000,0.611761,0.008581,0.052864,0.126885,0.899319,0.714828,0.646969,0.636020

In [4]:
original_df.head(5)

,pert_symbol,A1BG,A1CF,AADAC,AAK1,AARS1,AASS,ABCA1,ABCA12,ABCA5,...,ZP3,ZPBP,ZRANB3,ZSCAN18,ZSCAN31,ZSWIM5,ZSWIM6,ZSWIM7,ZWINT,ZYX
0,ACLY,0.311642,0.022102,0.100949,0.378671,0.715857,0.000000,0.118900,0.030792,0.087006,...,0.290693,0.002349,0.638608,0.031022,0.036856,0.097390,0.914845,0.647727,0.720461,0.603572
1,ALDOA,0.627445,0.043961,0.094335,0.442062,0.658125,0.000000,0.200191,0.000000,0.061549,...,0.390909,0.000000,0.371624,0.045867,0.087408,0.124600,0.821529,0.801302,0.545344,0.553567
2,APAF1,0.467114,0.030714,0.090910,0.470155,0.732770,0.002820,0.118370,0.025851,0.137382,...,0.359183,0.000000,0.535496,0.009991,0.053445,0.069219,0.855117,0.709241,0.674747,0.667791
3,ARID2,0.517185,0.018776,0.102561,0.445692,0.687079,0.010236,0.124519,0.016378,0.123456,...,0.353383,0.000000,0.557026,0.017552,0.062452,0.094811,0.731613,0.614643,0.629297,0.619404
4,BAG1,0.409021,0.034862,0.129969,0.462849,0.819877,0.002999,0.125579,0.002677,0.131047,...,0.286078,0.000000,0.611761,0.008581,0.052864,0.126885,0.899319,0.714828,0.646969,0.636020

In [5]:
diy_df = diy_df.rename(columns={diy_df.columns[0]: original_df.columns[0]})

In [6]:
original_df.equals(diy_df)

False

In [7]:
original_df.compare(diy_df)

        A1BG                A1CF               AADAC                AAK1  \
        self     other      self     other      self     other      self
0   0.311642  0.311642  0.022102  0.022102  0.100949  0.100949  0.378671
1   0.627445  0.627445       NaN       NaN       NaN       NaN  0.442062
2   0.467114  0.467114  0.030714  0.030714       NaN       NaN  0.470155
3   0.517185  0.517185  0.018776  0.018776  0.102561  0.102561  0.445692
4   0.409021  0.409021  0.034862  0.034862  0.129969  0.129969  0.462849
..       ...       ...       ...       ...       ...       ...       ...
76  0.537884  0.537884       NaN       NaN  0.106994  0.106994  0.455972
77       NaN       NaN       NaN       NaN  0.123302  0.123302  0.288553
78  0.498489  0.498489  0.009164  0.009164       NaN       NaN  0.420647
79  0.481894  0.481894       NaN       NaN  0.085533  0.085533  0.476920
80  0.474062  0.474062  0.025797  0.025797       NaN       NaN  0.443709

                 AARS1            ...    ZSWIM5              ZSWIM6            \
       other      self     other  ...      self     other      self     other
0   0.378671  0.715857  0.715857  ...       NaN       NaN  0.914845  0.914845
1   0.442062  0.658125  0.658125  ...  0.124600  0.124600       NaN       NaN
2   0.470155       NaN       NaN  ...  0.069219  0.069219  0.855117  0.855117
3   0.445692  0.687079  0.687079  ...       NaN       NaN  0.731613  0.731613
4   0.462849  0.819877  0.819877  ...  0.126885  0.126885  0.899319  0.899319
..       ...       ...       ...  ...       ...       ...       ...       ...
76  0.455972  0.723697  0.723697  ...  0.077293  0.077293  0.936977  0.936977
77  0.288553  0.675256  0.675256  ...       NaN       NaN  1.033585  1.033585
78  0.420647  0.753090  0.753090  ...       NaN       NaN  0.821152  0.821152
79  0.476920  0.801459  0.801459  ...  0.125091  0.125091  0.846153  0.846153
80  0.443709  0.737890  0.737890  ...  0.078303  0.078303  0.860658  0.860658

      ZSWIM7               ZWINT                 ZYX
        self     other      self     other      self     other
0        NaN       NaN  0.720461  0.720461  0.603572  0.603572
1   0.801302  0.801302  0.545344  0.545344  0.553567  0.553567
2   0.709241  0.709241  0.674747  0.674747  0.667791  0.667791
3   0.614643  0.614643  0.629297  0.629297  0.619404  0.619404
4   0.714828  0.714828  0.646969  0.646969  0.636020  0.636020
..       ...       ...       ...       ...       ...       ...
76  0.731447  0.731447  0.690297  0.690297  0.639862  0.639862
77  0.765131  0.765131  0.633493  0.633493  0.659664  0.659664
78  0.698710  0.698710  0.699610  0.699610       NaN       NaN
79  0.693998  0.693998  0.703783  0.703783  0.726951  0.726951
80  0.719807  0.719807  0.707353  0.707353  0.681142  0.681142

[81 rows x 10108 columns]

In [8]:
from pandas.testing import assert_frame_equal
assert_frame_equal(original_df, diy_df, check_exact=False, atol=1e-4, check_dtype=False)